// Build the DriX-8 ROS 2 topic reference .docx from tools/topic_inventory.json.
//
//   python tools/topic_inventory.py      # scan the bags -> topic_inventory.json
//   npm install --prefix tools docx      # one-off (tools/node_modules is gitignored)
//   node tools/build_topic_doc.js        # -> D:\Claude\ROS2\DriX8_ROS2_Topic_Reference.docx
//   powershell -File tools/bake_toc.ps1  # fill in the contents page
//
// Presentation only: every topic description lives in topic_inventory.py.
// Appendix A is hand-curated from the schemas embedded in the MCAP files —
// re-check it if the vehicle firmware changes.
const fs = require("fs");
const path = require("path");
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, WidthType, BorderStyle, ShadingType,
  LevelFormat, PageBreak, TableLayoutType,
  TableOfContents, Footer, PageNumber, TabStopType, LeaderType,
} = require("docx");

const DATA = JSON.parse(fs.readFileSync(path.join(__dirname, "topic_inventory.json"), "utf8"));
// The document lives outside this repo, so it is not versioned here and a
// build overwrites it in place. Pass a path as the first argument to write
// elsewhere. Absolute and machine-specific by necessity, hence the mkdir.
const OUT = process.argv[2] || "D:\\Claude\\ROS2\\DriX8_ROS2_Topic_Reference.docx";
fs.mkdirSync(path.dirname(OUT), { recursive: true });

// ---- palette / constants
const NAVY = "1F3864";
const STEEL = "2E5B8F";
const GRAY = "6B6B6B";
const SILENT = "8A8A8A";
const HDR_FILL = "DCE6F1";
const SUB_FILL = "F2F6FB";
const BORDER = { style: BorderStyle.SINGLE, size: 4, color: "B8C6D9" };
const CELL_BORDERS = { top: BORDER, bottom: BORDER, left: BORDER, right: BORDER };
const PAGE = { size: { width: 12240, height: 15840 },
               margin: { top: 864, bottom: 864, left: 864, right: 864 } };
const CW = 10512; // content width DXA

const MONO = "Consolas";

// ---- helpers
const t = (text, opts = {}) => new TextRun({ text, ...opts });
const para = (children, opts = {}) =>
  new Paragraph({ children: Array.isArray(children) ? children : [children], ...opts });

function body(text, opts = {}) {
  return new Paragraph({
    children: [t(text, { size: 20 })],
    spacing: { after: 120 }, ...opts,
  });
}
function bullet(runs) {
  return new Paragraph({
    children: runs.map(r => (typeof r === "string" ? t(r, { size: 20 }) : r)),
    numbering: { reference: "bullets", level: 0 },
    spacing: { after: 60 },
  });
}
function h1(text) {
  return new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 140 },
    children: [t(text, { size: 30, bold: true, color: NAVY })] });
}
function h2(text) {
  return new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 100 },
    children: [t(text, { size: 24, bold: true, color: STEEL })] });
}
function cell(children, width, opts = {}) {
  return new TableCell({
    children, width: { size: width, type: WidthType.DXA },
    borders: CELL_BORDERS, margins: { top: 40, bottom: 40, left: 80, right: 80 },
    ...opts,
  });
}
function hcell(text, width) {
  return cell([para(t(text, { size: 18, bold: true, color: NAVY }))], width,
    { shading: { type: ShadingType.CLEAR, fill: HDR_FILL } });
}
function table(colWidths, rows) {
  return new Table({
    columnWidths: colWidths, layout: TableLayoutType.FIXED,
    width: { size: colWidths.reduce((a, b) => a + b, 0), type: WidthType.DXA },
    rows,
  });
}

// ---- title block
const children = [];
children.push(new Paragraph({
  spacing: { before: 0, after: 60 },
  children: [t("DriX-8 Connectivity Box", { size: 52, bold: true, color: NAVY })],
}));
children.push(new Paragraph({
  spacing: { after: 160 },
  children: [t("ROS 2 Topic Reference", { size: 34, color: STEEL })],
}));
children.push(new Paragraph({
  spacing: { after: 60 },
  children: [
    t("Recordings: ", { size: 20, bold: true }),
    t("E:\\fuel\\D8_2040", { size: 20, font: MONO }),
    t("   ·   4–7 August 2026   ·   DriX-8, EM2040 gondola configuration", { size: 20 }),
  ],
}));
children.push(new Paragraph({
  spacing: { after: 240 },
  children: [t(
    `${DATA.n_topics} topics · ${(DATA.total_msgs / 1e6).toFixed(1)} million messages · ~77 hours of coverage · generated 7 August 2026`,
    { size: 20, color: GRAY })],
  border: { bottom: { style: BorderStyle.SINGLE, size: 8, color: NAVY } },
}));

// ---- table of contents
// "Contents" is deliberately NOT a Heading style — a heading here would list
// itself. Entries are generated by Word from the Heading 1/2 styles, so the
// numbering in h1()/h2() text ("4.7  …") is what appears; keep it accurate.
// features.updateFields below makes Word populate the field on open.
children.push(new Paragraph({
  spacing: { before: 120, after: 140 },
  children: [t("Contents", { size: 30, bold: true, color: NAVY })],
}));
children.push(new TableOfContents("Contents", {
  hyperlink: true,
  headingStyleRange: "1-2",
}));
children.push(new Paragraph({ children: [new PageBreak()] }));

// ---- 1. the recordings
children.push(h1("1.  The recordings"));
children.push(body(
  "These are rosbag2 recordings in MCAP format made by the recorder named connectivity_box_cc — the " +
  "control-centre (\u201Ccc\u201D) side of the DriX-8 data links. The bag captures the vehicle's telemetry as it " +
  "arrives over the links (Starlink, Wi-Fi, Iridium), together with the connectivity box's own local nodes " +
  "(fleet comm bridge, rosbridge servers for the operator HMI, clock-sync health). Vehicle topics live under " +
  "/drix_8/…; control-centre nodes live under /cortix/… at the root."));
children.push(body(
  "Each day is one bag split into ~100 MB chunks. The four days together:"));

const dayRows = [new TableRow({ tableHeader: true, children: [
  hcell("Day (UTC)", 1900), hcell("Coverage", 1500), hcell("Chunks", 1100),
  hcell("Messages", 1600), hcell("Notes", 4412),
]})];
const dayNotes = {
  "2026-08-04T00": "Recorder stopped ~16:35 UTC.",
  "2026-08-05T00": "Full day.",
  "2026-08-06T00": "Full day; largest of the set.",
  "2026-08-07T00": "Partial: no metadata.yaml (bag still open when copied) and chunk _4 is absent — roughly 1.3 h missing inside the day. Counts for this day were read from the MCAP summary sections directly.",
};
for (const [day, m] of Object.entries(DATA.days)) {
  dayRows.push(new TableRow({ children: [
    cell([para(t(day.replace("T00", ""), { size: 18, font: MONO }))], 1900),
    cell([para(t((m.duration_s / 3600).toFixed(1) + " h", { size: 18 }))], 1500),
    cell([para(t(String(m.files), { size: 18 }))], 1100),
    cell([para(t(m.message_count.toLocaleString("en-US"), { size: 18 }))], 1600),
    cell([para(t(dayNotes[day] || "", { size: 18 }))], 4412),
  ]}));
}
children.push(table([1900, 1500, 1100, 1600, 4412], dayRows));
children.push(new Paragraph({ spacing: { after: 60 }, children: [] }));
children.push(bullet([
  t("Chunk filenames sort lexically (…_1, _10, _11, _2…) — ", { size: 20 }),
  t("always order by record timestamp, never by filename", { size: 20, bold: true }),
  t(", when stitching a day back together.", { size: 20 }),
]));
children.push(bullet([
  "Topic counts include subscriptions that stayed silent — a defined topic with zero messages still appears in the inventory (marked “—”)."]));

// ---- 2. namespace
children.push(h1("2.  Reading the topic namespace"));
const conv = [
  ["/drix_8/…", "Vehicle topics, bridged from the DriX-8 over whichever link is up."],
  ["/cortix/…", "Nodes running locally on the control-centre connectivity box."],
  ["/drix_21/…  /drix_22/…", "Slots for other fleet hulls on the same bridge (silent in these logs)."],
  ["…/cc/…", "A feed shaped and bandwidth-budgeted specifically for the control-centre link."],
  ["light_*", "Bandwidth-trimmed variant of a heavier onboard topic (the full-rate original stays on the vehicle)."],
  ["d_<name>", "Device driver node (d_starlink, d_iridium, d_phins…)."],
  ["p_<name>", "Processing / utility node."],
  ["…/params, …/params_description, …/params_file", "Latched parameter snapshots of a node (current values / parameter docs / source YAML). Republished on (re)connection — counts track reconnects, not data. Folded into §5."],
];
const convRows = [new TableRow({ tableHeader: true, children: [
  hcell("Pattern", 3100), hcell("Meaning", 7412),
]})];
for (const [pat, meaning] of conv) {
  convRows.push(new TableRow({ children: [
    cell([para(t(pat, { size: 18, font: MONO }))], 3100),
    cell([para(t(meaning, { size: 18 }))], 7412),
  ]}));
}
children.push(table([3100, 7412], convRows));

// ---- 3. key topics
children.push(h1("3.  Topics of primary interest"));
children.push(body("The dozen topics that answer most questions about a mission, ordered by what they tell you:"));
const key = [
  ["/drix_8/cortix/communications/topic_simplifier/light_gps", "1.37", "Where the vehicle was and how fast it moved — lat/lon, SOG (m/s), COG, heading. Speed source of the fuel-curve refit."],
  ["/drix_8/cortix/plc/telemetry/telemetry3", "1.26", "Engine and fuel truth: fuel rate (L/h), total fuel used, temperatures, alarms. Fuel source of the refit."],
  ["/drix_8/cortix/plc/vehicle_status", "1.61", "Thruster RPM (the working RPM channel), rudder angle, fuel gauge %, mode, clutch, keel, e-stops."],
  ["/drix_8/cortix/communications/topic_simplifier/light_ins", "1.58", "Attitude and heave from the PHINS: roll, pitch, heading, quality statuses."],
  ["/drix_8/hardware/fuel_cons_manager/fuel_consumption", "0.98", "Onboard endurance projection: distance/time remaining to reserve at current speed and at 4/8/12 kt."],
  ["/drix_8/cortix/communications/d_starlink/status", "0.40", "Starlink dish health: throughput, POP ping, boresight, obstruction, outages — the vehicle's primary link."],
  ["/drix_8/cortix/communications/iridium/iridium_status", "9.83", "Iridium link watchdog: connection OK + last/next expected message."],
  ["/drix_8/cortix/plc/batteries/status", "0.40", "Electrical state: battery voltages/currents, alternator output."],
  ["/drix_8/cortix/mission/guidance_manager/guidance_state", "1.06", "What the vehicle was tasked to do and whether it was doing it (mode, state, OAS active)."],
  ["/drix_8/cortix/safety/supervisor/report", "0.39", "The safety verdict: every active fault at any moment."],
  ["/journal", "14.4", "All node log messages — the event-forensics stream."],
  ["/diagnostics", "21.6", "Raw per-device health firehose (aggregated in /diagnostics_agg)."],
];
const keyRows = [new TableRow({ tableHeader: true, children: [
  hcell("Topic", 4600), hcell("Hz", 700), hcell("What it gives you", 5212),
]})];
for (const [topic, hz, why] of key) {
  keyRows.push(new TableRow({ children: [
    cell([para(t(topic, { size: 15, font: MONO }))], 4600),
    cell([para(t(hz, { size: 18 }), { alignment: AlignmentType.RIGHT })], 700),
    cell([para(t(why, { size: 18 }))], 5212),
  ]}));
}
children.push(table([4600, 700, 5212], keyRows));

// ---- 4. full inventory
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("4.  Full topic inventory"));
children.push(body(
  "Every recorded topic, grouped by subsystem and ordered by publish rate within each group. " +
  "Rates are means over the days the topic appeared. Grey rows carried no traffic in these logs. " +
  "Parameter-snapshot topics (…/params*) are folded into the matrix in §5."));

let gi = 0;
for (const g of DATA.groups) {
  gi += 1;
  children.push(h2(`4.${gi}  ${g.title}  (${g.rows.length} topics)`));
  const introRuns = [t(g.intro + " ", { size: 20 })];
  if (g.prefix) {
    introRuns.push(t("Topic names below are shown relative to ", { size: 20, color: GRAY }));
    introRuns.push(t(g.prefix, { size: 18, font: MONO, color: GRAY }));
    introRuns.push(t(" unless they start with “/”.", { size: 20, color: GRAY }));
  }
  children.push(new Paragraph({ children: introRuns, spacing: { after: 100 } }));

  const rows = [new TableRow({ tableHeader: true, children: [
    hcell("Topic", 3050), hcell("Message type", 2050), hcell("Hz", 640), hcell("Description", 4772),
  ]})];
  for (const r of g.rows) {
    const silent = r.total === 0;
    const name = g.prefix && r.topic.startsWith(g.prefix)
      ? r.topic.slice(g.prefix.length) : r.topic;
    const color = silent ? SILENT : undefined;
    rows.push(new TableRow({ children: [
      cell([para(t(name, { size: 15, font: MONO, color }))], 3050),
      cell([para(t(r.type, { size: 15, font: MONO, color }))], 2050),
      cell([para(t(r.rate, { size: 17, color }), { alignment: AlignmentType.RIGHT })], 640),
      cell([para(t(r.desc, { size: 17, color }))], 4772),
    ]}));
  }
  children.push(table([3050, 2050, 640, 4772], rows));
}

// ---- 5. params matrix
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("5.  Node parameter topics"));
children.push(body(
  `${DATA.n_params_topics} of the ${DATA.n_topics} topics are latched parameter snapshots — up to three per node ` +
  "(V = current values, D = parameter descriptions, F = source YAML file), all std_msgs/String. " +
  "They document configuration, not telemetry. One row per node:"));
const pmRows = [new TableRow({ tableHeader: true, children: [
  hcell("Node", 4700), hcell("What it configures", 4012), hcell("V", 400), hcell("D", 400), hcell("F", 400), hcell("Msgs", 600),
]})];
for (const p of DATA.params_matrix) {
  const mk = (b) => cell([para(t(b ? "✓" : "", { size: 17 }), { alignment: AlignmentType.CENTER })], 400);
  pmRows.push(new TableRow({ children: [
    cell([para(t(p.node, { size: 14, font: MONO }))], 4700),
    cell([para(t(p.hint, { size: 17 }))], 4012),
    mk(p.values), mk(p.desc), mk(p.file),
    cell([para(t(String(p.total), { size: 16 }), { alignment: AlignmentType.RIGHT })], 600),
  ]}));
}
children.push(table([4700, 4012, 400, 400, 400, 600], pmRows));
children.push(new Paragraph({ spacing: { before: 80, after: 0 }, children: [
  t("A non-zero message count means the node (re)latched its parameters during the recording — e.g. the ", { size: 18, color: GRAY }),
  t("kongsberg_em_controller", { size: 16, font: MONO, color: GRAY }),
  t(" (the EM2040) republished 556 times, matching its role as the active survey payload.", { size: 18, color: GRAY }),
]}));

// ---- 6. data quality
children.push(h1("6.  Data-quality notes"));
const dq = [
  [t("The shaft RPM sensor was faulted through all four days", { size: 20, bold: true }),
   t(" — telemetry3.shaft_sensor_rpm reads 0/garbage. Use ", { size: 20 }),
   t("vehicle_status.thruster_rpm", { size: 18, font: MONO }),
   t(" (the PLC channel) for any RPM work.", { size: 20 })],
  [t("SOG in ", { size: 20 }), t("light_gps", { size: 18, font: MONO }),
   t(" is metres per second (multiply by 1.9438 for knots); COG and heading are degrees true.", { size: 20 })],
  [t("The onboard static endurance model (", { size: 20 }),
   t("fuel_consumption_model", { size: 18, font: MONO }),
   t(") reads ~1.9× the measured burn for this EM2040 configuration — its projections are very conservative.", { size: 20 })],
  [t("Three topics dominate volume: ", { size: 20 }),
   t("/diagnostics", { size: 18, font: MONO }), t(" (6.0 M), ", { size: 20 }),
   t("/journal", { size: 18, font: MONO }), t(" (4.0 M) and ", { size: 20 }),
   t("iridium_status", { size: 18, font: MONO }),
   t(" (2.7 M) — about half of all messages. Filter them out early when bulk-processing.", { size: 20 })],
  [t("Iridium snapshot topics (~121 messages each) are the low-rate fallback record — useful as a cross-check when broadband dropped.", { size: 20 })],
  [t("The 2026-08-07 day has a ~1.3 h hole where chunk _4 is missing; segment any time-series analysis across it.", { size: 20 })],
];
for (const runs of dq) children.push(bullet(runs));

// ---- appendix
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Appendix A — key message definitions"));
children.push(body(
  "Field definitions extracted from the schemas embedded in the MCAP files themselves " +
  "(so they match this firmware exactly). Abridged where noted."));

function msgTable(title, note, fields) {
  children.push(h2(title));
  if (note) children.push(new Paragraph({ children: [t(note, { size: 18, color: GRAY })], spacing: { after: 80 } }));
  const rows = [new TableRow({ tableHeader: true, children: [
    hcell("Field", 3000), hcell("Type", 1900), hcell("Meaning", 5612),
  ]})];
  for (const [name, typ, meaning] of fields) {
    rows.push(new TableRow({ children: [
      cell([para(t(name, { size: 15, font: MONO }))], 3000),
      cell([para(t(typ, { size: 15, font: MONO }))], 1900),
      cell([para(t(meaning, { size: 17 }))], 5612),
    ]}));
  }
  children.push(table([3000, 1900, 5612], rows));
}

msgTable("A.1  mdt_msgs/LightGps — light_gps", null, [
  ["stamp", "Time", "Measurement time (ROS time)."],
  ["latitude", "float64", "Decimal degrees, north positive."],
  ["longitude", "float64", "Decimal degrees, east positive."],
  ["altitude", "float32", "Metres relative to the surface."],
  ["cog", "float32", "Course over ground, degrees true (NaN when unavailable)."],
  ["sog", "float32", "Speed over ground, m/s (NaN when unavailable)."],
  ["heading", "float32", "Heading, degrees true."],
]);

msgTable("A.2  cortix_msgs/LightIns — light_ins", "Top level; statuses expand into PHINS algo/user status flags.", [
  ["roll / pitch / heading", "float32", "Attitude, degrees."],
  ["heave", "float32", "Heave, metres."],
  ["std_heading / std_horizontal", "float32", "1σ heading and horizontal-position uncertainty."],
  ["statuses", "InsStatuses", "PHINS alignment state, dead-reckoning flag, altitude source flags."],
  ["fix_quality_gps1 / gps2", "int32", "Fix quality of each GNSS receiver feeding the INS."],
]);

msgTable("A.3  drix_msgs/DrixOutput — vehicle_status", null, [
  ["thruster_rpm", "int16", "Thruster RPM measurement — the working RPM source in these logs."],
  ["rudder_angle_deg", "float32", "Rudder angle, clockwise degrees, 0 = astern reference, −180…+180."],
  ["gasoline_level_percent", "int8", "Fuel tank gauge, 0–100 %. Measured scale 2.06 ± 0.11 L per indicated point over the 72–86 % band — 4σ below the 2.50 a linear 250 L tank implies. Non-linearity is unresolved (per-day spread 1.5σ), not established; every reading is from the top third of the tank."],
  ["drix_mode", "uint8", "0 = DOCKING, 1 = MANUAL, 2 = AUTO."],
  ["drix_clutch", "uint8", "0 = ERROR, 1 = BACKWARD, 2 = NEUTRAL, 3 = FORWARD."],
  ["keel_state", "uint8", "1 = UP, 2 = MIDDLE, 3 = DOWN; 0/10/11/12 = error states."],
  ["emergency_mode / low_power_mode", "bool", "Vehicle emergency and electrical-economy flags."],
  ["rc_/cable_/hmi_emergency_stop", "bool", "Which e-stop chain is asserted."],
  ["error_code / error_string", "uint16 / string", "Non-zero / non-empty on PLC communication problems."],
  ["shutdown_status", "uint8", "0 = none, 1 = shutdown requested, 2 = reboot requested."],
]);

msgTable("A.4  drix_msgs/Telemetry3 — plc/telemetry/telemetry3", "Abridged — the full definition carries ~100 fields (compartment alarms, engine diagnostics, sensor-fault flags, spares).", [
  ["fuel_rate_lph", "float32", "Instantaneous fuel burn, L/h — the refit's fuel source."],
  ["total_fuel_used_l", "uint32", "Cumulative fuel used, in units of 0.01 L."],
  ["shaft_sensor_rpm", "uint16", "Optional shaft RPM sensor — faulted (0/garbage) in all four days."],
  ["engine_hours", "float64", "Engine total runtime, h."],
  ["engine_oil_pressure", "float32", "0–10 bar."],
  ["engine_coolant_temperature", "float32", "0–210 °C."],
  ["engine_exhaust_temperature / gearbox_oil_temperature", "float32", "°C."],
  ["engine_load / engine_accelerator_position", "float32", "Engine load and throttle position (VERSION2 fields)."],
  ["battery_1/2_voltage, _current, _percentage", "float32", "Battery electrics; plus alternator_1/2_current, diode volts/amps."],
  ["uptime / delivery_uptime", "uint32", "Seconds since power-on / cumulative hours since build."],
  ["engine_on, engine_alarm, water_in_fuel, …", "bool", "Machinery alarm and status flags (~40 booleans)."],
]);

msgTable("A.5  cortix_msgs/StarlinkDishStatus — d_starlink/status", "Top level — mirrors the dish's local gRPC API (the same one the Starlink Dashboard polls). Sub-messages carry device info/state, alerts, outage record, GPS stats, obstruction stats and ready states.", [
  ["downlink_throughput_bps / uplink_throughput_bps", "float32", "Current link throughput."],
  ["pop_ping_latency_ms / pop_ping_drop_rate", "float32", "Latency and loss to the Starlink point of presence."],
  ["boresight_azimuth_deg / boresight_elevation_deg", "float32", "Dish pointing."],
  ["obstruction_stats", "StarlinkDishObstructionStats", "Obstruction fraction/events."],
  ["outage", "StarlinkDishOutage", "Last/current outage record."],
  ["gps_stats", "StarlinkDishGpsStats", "Dish GPS validity and satellite count."],
  ["ready_states", "StarlinkDishReadyStates", "Subsystem bring-up flags."],
  ["mobility_class / class_of_service", "uint8", "0 = stationary, 1 = nomadic, 2 = mobile; service tier."],
  ["disablement_code", "uint8", "1 = OKAY; 4 = IN_OCEAN; account/geo disablement reasons."],
  ["eth_speed_mbps", "int32", "Negotiated Ethernet speed."],
  ["is_snr_above_noise_floor / is_snr_persistently_low", "bool", "Signal-quality flags."],
  ["software_update_state / stow_requested / has_actuators", "uint8/bool", "Housekeeping."],
]);

msgTable("A.6  cortix_msgs/FuelConsumption — fuel_cons_manager/fuel_consumption", null, [
  ["current_consumption", "float32", "Burn at current speed, L/h."],
  ["distance_to_go_m / duration_to_go", "float32 / Duration", "Range and endurance remaining to the reserve at current speed."],
  ["distance_4kn_m / 8kn / 12kn", "float32", "Range remaining at fixed 4/8/12 kt."],
  ["duration_4kn / 8kn / 12kn", "Duration", "Endurance remaining at fixed 4/8/12 kt."],
  ["consumption_4kn / 8kn / 12kn", "float32", "Model burn at 4/8/12 kt, L/h."],
  ["dynamic_model_used", "bool", "Whether the dynamic (vs static) capacity model produced the numbers."],
]);

msgTable("A.7  cortix_msgs/FuelConsumptionModel — fuel_consumption_model", null, [
  ["a / b / c", "float32", "Burn quadratic L/h = a·v² + b·v + c, v = SOG in knots."],
  ["tank_capacity", "float32", "Tank capacity used by the model, litres."],
  ["min_tank_percentage", "float32", "Reserve floor, %."],
]);

msgTable("A.8  drix_msgs/BatteriesStatus — plc/batteries/status", null, [
  ["battery_1 / battery_2", "BatteryStatus", "voltage (V), current (A), low/high-voltage, low-capacity, discharging, in-charge flags."],
  ["alternator_1 / alternator_2", "AlternatorStatus", "current (A), no-current, high-voltage, stopped-by-PLC flags."],
]);

msgTable("A.9  cortix_msgs/IridiumStatus — iridium/iridium_status", null, [
  ["stamp", "Time", "Report time."],
  ["last_valid_msg_reception", "Time", "When the last valid Iridium message arrived."],
  ["next_expected_msg_reception", "Time", "Deadline for the next expected message."],
  ["is_connection_ok", "bool", "Link watchdog verdict."],
]);

msgTable("A.10  cortix_msgs/GuidanceStatus — guidance_state", null, [
  ["guidance_mode", "string", "Active guidance type (waypoint following, station keeping…)."],
  ["guidance_state", "string", "STARTED / STOPPED / PAUSED / FAILED / SELECTED."],
  ["description", "string", "Reason for the current state."],
  ["is_oas_active", "bool", "Obstacle-avoidance currently active."],
  ["iridium_mode", "bool", "Guidance running under Iridium fallback C2."],
]);

// ---- footer note
children.push(new Paragraph({ spacing: { before: 300 }, children: [
  t("Generated from the MCAP summaries and embedded schemas of E:\\fuel\\D8_2040 on 7 August 2026. ",
    { size: 16, color: GRAY }),
  t("Rates are whole-recording means; bursty topics (screenshots, transfers) publish unevenly.",
    { size: 16, color: GRAY }),
]}));

// Page numbers in the footer — a TOC citing "page 9" is only useful if the
// pages say which one they are.
const footer = new Footer({
  children: [new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [
      t("DriX-8 ROS 2 Topic Reference   ·   page ", { size: 16, color: GRAY }),
      new TextRun({ children: [PageNumber.CURRENT], size: 16, color: GRAY }),
      t(" of ", { size: 16, color: GRAY }),
      new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: GRAY }),
    ],
  })],
});

// TOC entry styles. Word invents these when it updates the field, which is why
// the page numbers looked right before — but that repair is Word's, not the
// file's, so any other renderer got the page number at a default 0.5" tab
// instead of the right margin. Defining them makes the layout the document's
// own. Names must be exactly "toc 1"/"toc 2": that is how Word matches an
// entry level to its style.
const tocStyle = (id, name, indent) => ({
  id, name, basedOn: "Normal", next: "Normal", quickFormat: true,
  paragraph: {
    spacing: { before: 30, after: 30 },
    ...(indent ? { indent: { left: indent } } : {}),
    tabStops: [{ type: TabStopType.RIGHT, position: CW, leader: LeaderType.DOT }],
  },
});

const doc = new Document({
  features: { updateFields: true },   // Word fills the TOC field on open
  styles: {
    default: {
      document: { run: { font: "Calibri", size: 20 } },
    },
    paragraphStyles: [
      tocStyle("TOC1", "toc 1", 0),
      tocStyle("TOC2", "toc 2", 280),
    ],
  },
  numbering: {
    config: [{
      reference: "bullets",
      levels: [{
        level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,
        style: { paragraph: { indent: { left: 360, hanging: 200 } } },
      }],
    }],
  },
  sections: [{ properties: { page: PAGE }, footers: { default: footer }, children }],
});

Packer.toBuffer(doc).then((buf) => {
  fs.writeFileSync(OUT, buf);
  console.log("wrote", OUT, buf.length, "bytes");
  // The contents field is empty in this output — a build alone leaves the page
  // blank everywhere except Word. Say so, loudly, every time.
  console.log("NEXT: powershell -File tools/bake_toc.ps1   " +
              "(fills the contents page; without it only Word shows entries)");
});
